### PR TITLE
Move the list of notifications into QML so we get fancy animations

### PR DESCRIPTION
**Pull request by iBeliever**
Each time a notification was created, it reloaded the entire list, which prevented fancy animations. I set up signals that the QML can connect to, so it can then be handled via a ListModel in QML, allowing for some fancy animations which I will demo soon.

### CODE REVIEW

**Comment by boghison** [comment]
I think this is actually a bug in Qt ([here](http://stackoverflow.com/questions/22036160/how-to-have-transition-animations-when-using-qml-listview-and-c-qlistqobject))

**Comment by iBeliever** [comment]
@boghison No, it's just a limitation of QList, though I suppose you could call it a bug. What do you think of merging this in?

**Comment by boghison** [comment]
Well I guess you can merge it if you really want those fancy notifications :P BTW, I think the spec says that when a notification is replaced, it must be done instantly, just a tip :)

**Comment by iBeliever** [comment]
@boghison Just wait a minute (I'm about to post a demo video), and you'll see why - it looks super nice :)

Yep, still working on updating notifications (QML is being naughty), but I do plan to update it instantly.

**Comment by boghison** [comment]
Hmm, didn't look at the your code that meticulously so idk why QML is being "naughty". In my demo I showed that replacing notifications was working fine :)

**Pull request merged**
